### PR TITLE
fixed bridge deployment

### LINKED ISSUE #191: wrong assumption
the deployment of the bridge is failing. 

```
018-09-06 11:28:31  main INFO parity::run  Starting Parity/v1.11.7-stable-085035f-20180717/x86_64-macos/rustc1.27.1
2018-09-06 11:28:31  main INFO parity::run  Keys path /Users/mkuechler/Library/Application Support/io.parity.ethereum/keys/Kovan
2018-09-06 11:28:31  main INFO parity::run  DB path /Users/mkuechler/Library/Application Support/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98
2018-09-06 11:28:31  main INFO parity::run  Path to dapps /Users/mkuechler/Library/Application Support/io.parity.ethereum/dapps
2018-09-06 11:28:31  main INFO parity::run  State DB configuration: fast
2018-09-06 11:28:31  main INFO parity::run  Operating mode: active
2018-09-06 11:28:32  main INFO ethcore_service::service  Configured for Kovan using AuthorityRound engine
2018-09-06 11:28:37  IO Worker #1 INFO network  Public node URL: enode://cf094185883fd4cdb517a3990d1d5ccdfc64f423c1fbcc69928850623204dd76e9e61612c686bffd3a18d50dad52b1ccef3554ceaaaa71d493cb593185fd7fd2@192.168.0.75:30304
2018-09-06 11:28:39  IO Worker #2 INFO import  Imported #8627123 0x0fee…1aa6 (2 txs, 0.47 Mgas, 2 ms, 2.20 KiB) + another 1 block(s) containing 0 tx(s)
2018-09-06 11:28:44  Verifier #6 INFO import  Imported #8627124 0x381a…d1aa (1 txs, 0.02 Mgas, 5 ms, 0.68 KiB)
2018-09-06 11:28:57   TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":"0x608060405234801561001057600080fd5b50604051610a0c380380610a0c83398101604090815281516020830151918301516060840151608085015192949390930192909184151561005057600080fd5b835185111561005e57600080fd5b6000859055835161007690600490602087019061008b565b50600192909255600255600355506101179050565b8280548282559060005260206000209081019282156100e0579160200282015b828111156100e05782518254600160a060020a031916600160a060020a039091161782556020909201916001909101906100ab565b506100ec9291506100f0565b5090565b61011491905b808211156100ec578054600160a060020a03191681556001016100f6565b90565b6108e6806101266000396000f3006080604052600436106100775763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416633c3aa83981146100ec578063494503d41461011357806367faa5191461014757806382bbe3651461015c5780638d068043146101715780639ce318f614610186575b600354158061008857506003543411155b151561009357600080fd5b60025415806100a55750600254303111155b15156100b057600080fd5b6040805133815234602082015281517fe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c929181900390910190a1005b3480156100f857600080fd5b5061010161028d565b60408051918252519081900360200190f35b34801561011f57600080fd5b5061012b600435610293565b60408051600160a060020a039092168252519081900360200190f35b34801561015357600080fd5b506101016102bb565b34801561016857600080fd5b506101016102c1565b34801561017d57600080fd5b506101016102c7565b34801561019257600080fd5b506040805160206004803580820135838102808601850190965280855261028b95369593946024949385019291829185019084908082843750506040805187358901803560208181028481018201909552818452989b9a998901989297509082019550935083925085019084908082843750506040805187358901803560208181028481018201909552818452989b9a99890198929750908201955093508392508501908490808284375050604080516020601f89358b018035918201839004830284018301909452808352979a9998810197919650918201945092508291508401838280828437509497506102cd9650505050505050565b005b60025481565b60048054829081106102a157fe5b600091825260209091200154600160a060020a0316905081565b60035481565b60015481565b60005481565b600080600080600080865160741415156102e657600080fd5b610350878b8b8b600480548060200260200160405190810160405280929190818152602001828054801561034357602002820191906000526020600020905b8154600160a060020a03168152600190910190602001808311610325575b50505050506000546104a3565b151561035b57600080fd5b61036487610626565b955061036f8761062d565b945061037a87610634565b93506103858761063b565b9250600160a060020a03861633148061039d5750823a145b15156103a857600080fd5b60008481526005602052604090205460ff16156103c457600080fd5b5050600082815260056020526040808220805460ff191660019081179091555490519083029182860391600160a060020a0388169183156108fc02918491818181858888f1935050505015801561041f573d6000803e3d6000fd5b50604051339083156108fc029084906000818181858888f1935050505015801561044d573d6000803e3d6000fd5b5060408051600160a060020a03881681526020810183905280820186905290517f4d911754a3efbbc2e0463de4f6bff32ed24421d1c89c11dce59a4935f327afff9181900360600190a150505050505050505050565b6000806060600080858a5110156104bd5760009450610618565b6104c68b610642565b935086516040519080825280602002602001820160405280156104f3578160200160208202803883390190505b509250600091505b85821015610613576001848b8481518110151561051457fe5b906020019060200201518b8581518110151561052c57fe5b906020019060200201518b8681518110151561054457fe5b60209081029091018101516040805160008082528185018084529790975260ff9095168582015260608501939093526080840152905160a0808401949293601f19830193908390039091019190865af11580156105a5573d6000803e3d6000fd5b5050506020604051035190506105bb878261077e565b15156105ca5760009450610618565b6105d4838261077e565b156105e25760009450610618565b8083838151811015156105f157fe5b600160a060020a039092166020928302909101909101526001909101906104fb565b600194505b505050509695505050505050565b6014015190565b6034015190565b6054015190565b6074015190565b600060606040805190810160405280601a81526020017f19457468657265756d205369676e6564204d6573736167653a0a00000000000081525090508061068984516107d9565b846040518084805190602001908083835b602083106106b95780518252601f19909201916020918201910161069a565b51815160209384036101000a600019018019909216911617905286519190930192860191508083835b602083106107015780518252601f1990920191602091820191016106e2565b51815160209384036101000a600019018019909216911617905285519190930192850191508083835b602083106107495780518252601f19909201916020918201910161072a565b5181516020939093036101000a6000190180199091169216919091179052604051920182900390912098975050505050505050565b6000805b83518110156107cd5782600160a060020a031684828151811015156107a357fe5b90602001906020020151600160a060020a031614156107c557600191506107d2565b600101610782565b600091505b5092915050565b606060008282825b600190930192600a8304925082156107f8576107e1565b836040519080825280601f01601f191660200182016040528015610826578160200160208202803883390190505b5086935091505060001983015b81516000198201917f01000000000000000000000000000000000000000000000000000000000000006030600a8706010291849190811061087057fe5b9060200101907effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916908160001a905350600a8304925082156108b157610833565b509493505050505600a165627a7a72305820d4a4a6a34b43648c06a246669122be4d8c2ba4fddf44230d80ba74705aff03ad0029000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000030d400000000000000000000000000000000000000000000000008ac7230489e800000000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000006b5dda44dc2606f07ad86c9190fb54fd905f6d00000000000000000000000000d7f73c515c8470b647e2ba22673d314d536e6f00000000000000000000000000e2e6baf017ae211693f203f0a629b21022d087","from":"0x006b5dda44dc2606f07ad86c9190fb54fd905f6d","gas":"0xf4240","gasPrice":"0x0"}],"id":1}.
2018-09-06 11:28:57   DEBUG rpc  [Some(Num(1))] Took 43ms
2018-09-06 11:28:57   DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x36efc16910ea67a2425a1e75f7e39e3c6a94f5763c68a47258f552481e20cd34","id":1}.
2018-09-06 11:28:57   TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":2}.
2018-09-06 11:28:57   DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0","id":2}.
2018-09-06 11:28:58   TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x0"],"id":3}.
2018-09-06 11:28:58   DEBUG rpc  Response: {"jsonrpc":"2.0","result":[],"id":3}.
2018-09-06 11:28:59   TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x0"],"id":4}.
2018-09-06 11:28:59   DEBUG rpc  Response: {"jsonrpc":"2.0","result":[],"id":4}.
2018-09-06 11:29:00  Verifier #5 INFO import  Imported #8627126 0x4d6d…f60f (3 txs, 0.12 Mgas, 6 ms, 1.12 KiB) + another 1 block(s) containing 5 tx(s)
2018-09-06 11:29:00   TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x0"],"id":5}.
2018-09-06 11:29:00   DEBUG rpc  Response: {"jsonrpc":"2.0","result":["0x4d6df21f9ccfd79a00131e0e8c29274abc3615b3b9de5f63e8759127ef03f60f"],"id":5}.
2018-09-06 11:29:00   TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x36efc16910ea67a2425a1e75f7e39e3c6a94f5763c68a47258f552481e20cd34"],"id":6}.
2018-09-06 11:29:00   DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"blockHash":null,"blockNumber":null,"contractAddress":"0xb1ac3a5584519119419a8e56422d912c782d8e5b","cumulativeGasUsed":"0x1c1999","gasUsed":"0xcdb5d","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","root":null,"status":"0x1","transactionHash":"0x36efc16910ea67a2425a1e75f7e39e3c6a94f5763c68a47258f552481e20cd34","transactionIndex":"0x4"},"id":6}.
2018-09-06 11:29:02  IO Worker #2 INFO import    #2886764    4/25 peers   6 MiB chain 65 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  1 req/s, 154 µs
2018-09-06 11:29:04  Verifier #0 INFO import  Imported #8627127 0x7c6a…a273 (3 txs, 0.13 Mgas, 1 ms, 1.27 KiB)
2018-09-06 11:29:12  Verifier #3 INFO import  Imported #8627128 0x7df1…63cd (1 txs, 1.07 Mgas, 60 ms, 1.24 KiB)
2018-09-06 11:29:20  Verifier #6 INFO import  Imported #8627129 0xb0b6…be6c (2 txs, 0.65 Mgas, 53 ms, 1.00 KiB)
2018-09-06 11:29:24  IO Worker #3 INFO own_tx  Transaction mined (hash 0x36efc16910ea67a2425a1e75f7e39e3c6a94f5763c68a47258f552481e20cd34)
201
```

### LINKED ISSUE #196: send_transaction_with_confirmation fails at parity-bridge-deploy
## Environment : 
- OS ubuntu with [this bootstrap](https://github.com/branciard/blockchain-dev-env/blob/master/bootstrap-ubuntu-aws.sh) 
- Parity docker image version: parity/parity:stable
- Parity config POA using [parity-deploy](https://github.com/paritytech/parity-deploy) : 
```
./parity-deploy.sh --config aura --name ${CHAIN_NAME} --nodes ${CHAIN_NODES} --ethstats --expose
```
## Error : 

```
env RUST_LOG=debug ./release/parity-bridge-deploy --config ../iexec-bridge-test.toml --database ./db.toml
```
Deploy contract transaction in mined successfully in ethereum-parity client logs : 
```
host1        | 2018-09-25 13:28:48 UTC Transaction mined (hash 0xe2ba7441691034a279bba39b9179b5dd78560c17b43d86e504a33f58daf6b52d)
```
But the client fails with the following error : 
```
thread 'main' panicked at 'receipt can't be null after wait for confirmations; qed', libcore/option.rs:989:5
```

## Solution : 

I forked the [rust-web3](https://github.com/tomusdrw/rust-web3)  and add a tempo (basically wait transaction to be mined and receipt ready) in the branch here [add-tempo](https://github.com/branciard/rust-web3/commit/fd8638e2b30a285a5d39dd50836da6d63237dc26) to dirty quick test. 
I change the dependancy in Cargo.toml : 
```
web3 = { git = "https://github.com/branciard/rust-web3", branch = "add-tempo"  }
```
With this quick dirty fix, parity-bridge-deploy passed for home and foreign bridge contracts creation.

Do you think it is more an issue in rust-web3 client lib ? 
and I should open in rust-web3 github repo ?

### PR DESCRIPTION
**Pull request by debris**
issues:
- closes #191 
- closes #196

changes:

- new `Stream` -> `BlockNumberStream` which yields confirmed blocks
- new `Future` -> `SendTransactionWithReceipt` which replaces buggy `web3::send_transaction_with_confirmation`

before merge:
- requires https://github.com/tomusdrw/rust-web3/pull/164

what caused the issue?

`eth_getTransactionReceipt` returns receipt with fields `block_hash` and `block_number` set to `null` for transactions that are a part of pending block. update to `rust-web3` fixes `TransactionReceipt` structure to take it into account, whereas `SendTransactionWithReceipt` stream waits for receipt until transaction becomes a member of a block with sufficient number of confirmations

### CODE REVIEW

File: bridge/src/block_number_stream.rs [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+
+pub struct BlockNumberStreamOptions<T> {
+    pub request_timeout: Duration,
+    pub poll_interval: Duration,
+    pub confirmations: u32,
+    pub transport: T,
+    pub after: u64,
+}
+
+/// `Stream` that repeately polls `eth_blockNumber` and yields new block numbers.
```
Comment (tomusdrw) [inline bridge/src/block_number_stream.rs]: `repeatedly`

File: bridge/src/log_stream.rs [hunk 2]
```diff
@@ -119,53 +126,31 @@ impl<T: Transport> Stream for LogStream<T> {
...
-                        self.topic
-                    )));
-                    info!(
-                        "LogStream (topic: #{:?}): polling last block number",
-                        self.topic
+                State::AwaitBlockNumber => {
+                    let last_block = try_stream!(
+                        self.block_number_stream
+                            .poll()
+                            .chain_err(|| "LogStream: fetching of last confirmed block number failed")
```
Comment (tomusdrw) [inline bridge/src/log_stream.rs]: Might be better to actually re-try the call instead of failing here, but I guess it's beyond scope of this PR, as I suspect it's probably the assumption across the entire codebase that the RPC is always available.

File: bridge/src/log_stream.rs [hunk 3]
```diff
@@ -119,53 +126,31 @@ impl<T: Transport> Stream for LogStream<T> {
...
                     );
-                    let future = web3::api::Eth::new(&self.transport).block_number();
-                    let next_state = State::AwaitBlockNumber(
-                        self.timer.timeout(future.from_err(), self.request_timeout),
+                    info!("LogStream: fetched confirmed block number {}", last_block);
+
+                    let from = self.last_checked_block + 1;
```
Comment (tomusdrw) [inline bridge/src/log_stream.rs]: I guess this kind of approach my not handle re-orgs well. I.e. you look for logs in say (4, 6) and then you will only look in (6, 7) even though 5,6 could actually re-organize, but `block_stream` does not return any new blocks for you.

I suppose it's fine though, cause we have the `confirmations` in the block stream, so it should only return blocks that are unlikely to re-organize.

File: bridge/src/send_tx_with_receipt.rs [hunk 4]
```diff
@@ -0,0 +1,368 @@
...
+                        let hash = try_ready!(
+                            future
+                                .poll()
+                                .chain_err(|| "SendTransactionWithReceipt: sending transaction failed")
+                        );
+                        info!("SendTransactionWithReceipt: sent transaction {}", hash);
+                        State::AwaitBlockNumber(hash)
+                    },
+                    State::AwaitBlockNumber(transaction_hash) => {
+                        let last_block = match self.block_number_stream.poll() {
```
Comment (tomusdrw) [inline bridge/src/send_tx_with_receipt.rs]: Why not `try_ready!`?

File: bridge/src/send_tx_with_receipt.rs [hunk 5]
```diff
@@ -0,0 +1,368 @@
...
+        loop {
+            let next_state = match self.state {
+                State::AwaitBlockNumber { ref mut future, ref mut transaction } => {
+                    let block_number = try_ready!(
+                        future
+                            .poll()
+                            .chain_err(|| "SendTransactionWithReceipt: fetching last block number failed")
+                    );
+                    info!("SendTransactionWithReceipt: got last block number {}", block_number);
+                    let transaction = transaction.take().expect("transaction should always be set");
```
Comment (tomusdrw) [inline bridge/src/send_tx_with_receipt.rs]: Should be more proofy - just mention that we are in `AwaitBlockNumber` state only initially and transaction is always `Some` initially.

File: bridge/src/send_tx_with_receipt.rs [hunk 6]
```diff
@@ -0,0 +1,368 @@
...
+            request_timeout: options.request_timeout,
+            poll_interval: options.poll_interval,
+            transport: options.transport,
+            state,
+            confirmations: options.confirmations,
+        }
+    }
+}
+
+impl<T: Transport> Future for SendTransactionWithReceipt<T> {
```
Comment (tomusdrw) [inline bridge/src/send_tx_with_receipt.rs]: Couldn't this be done simply with `.then` combinator of future?
i.e:
```
block_number_stream.into_future().then(|(block_number, _)| {
  inner::SendTransactionWithReceipt(inner::SendTransactionWithReceiptOptions {
   ...
  })
})

File: bridge/src/log_stream.rs (hunk 2 above)
Comment (debris) [reply bridge/src/log_stream.rs]: yes, it is

Comment (debris) [reply bridge/src/log_stream.rs]: I believe we could fix this on a transport layer for all requests

File: bridge/src/log_stream.rs (hunk 3 above)
Comment (debris) [reply bridge/src/log_stream.rs]: yes, the assumption is that we reorgs are < `confirmations`

File: bridge/src/send_tx_with_receipt.rs (hunk 6 above)
Comment (debris) [reply bridge/src/send_tx_with_receipt.rs]: hmm.. maybe it could be simplified with `web3::api::Eth::new(&transport).block_number().and_then(|(block_number)`  if also use `impl trait` as a result type. But at the same time, I kind of find this more explicit implementation to be cleaner and more descriptive :)

File: bridge/src/log_stream.rs (hunk 2 above)
Comment (tomusdrw) [reply bridge/src/log_stream.rs]: Yup, `ReTryingTransport` could be a thing (same as `TimeoutTransport` actually).
